#!/usr/bin/env python3
"""Restore Protect events from a v7.1 partial pg_dump backup into the current
Protect Postgres database, translating numeric label IDs between the two
schemas.

Source:  a temp PG16 container that already has the backup restored, reachable
         at SOURCE_DSN (defaults to localhost:5444).
Sink:    the live Protect cluster on the router.  This script never connects
         to it directly; it writes a self-contained SQL file that you scp to
         the router and apply with:

             psql -h /run/postgresql -p 5433 -U postgres unifi-protect -f restore.sql

Scope is constrained by --camera-id and --date so we can verify one slice in
the UI before expanding.  IDs are preserved end-to-end so re-runs are idempotent
(ON CONFLICT DO NOTHING)."""

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

import psycopg2
import psycopg2.extras


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source-dsn", default="host=127.0.0.1 port=5444 user=postgres password=test dbname=unifi-protect")
    p.add_argument("--camera-id", default="",
                   help="Protect cameraId. If empty, restore every camera.")
    p.add_argument("--date", default="",
                   help="UTC day YYYY-MM-DD. If empty, restore every date.")
    p.add_argument("--current-labels", required=True,
                   help="Path to JSON file mapping current `labels.name` -> `labels.lid` (dump from current DB)")
    p.add_argument("--out", required=True, help="Output SQL file path")
    return p.parse_args()


def load_current_labels(path: Path) -> dict[str, int]:
    with path.open() as f:
        rows = json.load(f)
    return {r["name"]: int(r["lid"]) for r in rows}


def quote_text(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def quote_json(j) -> str:
    if j is None:
        return "NULL"
    if isinstance(j, (dict, list)):
        s = json.dumps(j, separators=(",", ":"))
    else:
        s = str(j)
    return "'" + s.replace("'", "''") + "'::json"


def quote_int_array(arr) -> str:
    if arr is None:
        return "NULL"
    return "ARRAY[" + ",".join(str(int(x)) for x in arr) + "]::int[]"


def main() -> int:
    args = parse_args()

    # Build optional WHERE clauses + parameters.
    where, params = ['"cameraId" IS NOT NULL'], []
    if args.camera_id:
        where.append('"cameraId" = %s')
        params.append(args.camera_id)
    if args.date:
        day = dt.datetime.strptime(args.date, "%Y-%m-%d").replace(tzinfo=dt.timezone.utc)
        day_start_ms = int(day.timestamp() * 1000)
        where.append('start >= %s AND start < %s')
        params.extend([day_start_ms, day_start_ms + 86_400_000])

    current_label_to_lid = load_current_labels(Path(args.current_labels))

    conn = psycopg2.connect(args.source_dsn)
    conn.set_session(readonly=True)
    src = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

    # ----- Build backup label-id -> name map (only labels actually used) -----
    src.execute('SELECT lid, name FROM labels')
    src_lid_to_name = {row["lid"]: row["name"] for row in src.fetchall()}

    # ----- Pull events matching the filters -----
    sql = "SELECT * FROM events WHERE " + " AND ".join(where) + " ORDER BY start"
    src.execute(sql, params)
    events = src.fetchall()
    if not events:
        print(f"No events for filter cameraId={args.camera_id or 'ALL'} date={args.date or 'ALL'}", file=sys.stderr)
        return 1
    event_ids = [e["id"] for e in events]

    # ----- Pull detectionLabels for those events -----
    src.execute(
        'SELECT * FROM "detectionLabels" WHERE "eventId" = ANY(%s)',
        (event_ids,),
    )
    det_labels = src.fetchall()

    # ----- Resolve labels: figure out which strings we need to upsert -----
    # Walk every label-id used in det_labels.labels[]; translate via src_lid_to_name.
    needed_label_names: set[str] = set()
    for dl in det_labels:
        for lid in dl["labels"] or []:
            name = src_lid_to_name.get(lid)
            if name is not None:
                needed_label_names.add(name)

    # ----- Emit SQL -----
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write(f"-- generated by tools/restore_events_from_backup.py\n")
        f.write(f"-- source dsn: {args.source_dsn}\n")
        f.write(f"-- camera_id : {args.camera_id or 'ALL'}\n")
        f.write(f"-- date      : {args.date or 'ALL'} UTC\n")
        f.write(f"-- events    : {len(events)}\n")
        f.write(f"-- det labels: {len(det_labels)}\n")
        f.write("\nBEGIN;\n\n")

        # Step 1: ensure every needed label exists in current.  We can't be sure
        # what lid it lands at (labels_lid_seq is shared), but we get a fresh
        # lid via INSERT ... ON CONFLICT (name) DO UPDATE ... RETURNING lid
        # is not portable enough for a one-shot file.  So instead we use the
        # provided current_label_to_lid map (dumped from current DB before the
        # script runs) and only upsert names that are NOT in the map yet —
        # those get a placeholder lid we compute server-side via a CTE.
        # For now we just UPSERT by name; if the name already exists this is
        # a no-op.  We need a stable per-name `id` UUID — use a deterministic
        # one derived from the name so re-runs don't duplicate.
        f.write("-- 1. upsert missing labels\n")
        for name in sorted(needed_label_names):
            if name in current_label_to_lid:
                continue
            # Generate a deterministic UUIDv5 from the name so re-runs are stable.
            import uuid
            label_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, f"protect:label:{name}"))
            f.write(
                f"INSERT INTO labels (name, id, \"createdAt\", \"updatedAt\") "
                f"VALUES ({quote_text(name)}, {quote_text(label_uuid)}, now(), now()) "
                f"ON CONFLICT (name) DO NOTHING;\n"
            )
        f.write("\n")

        # Step 2: build a (backup_lid -> CURRENT lid) translation lookup as a
        # temp table, so detectionLabels INSERTs can re-map their int[] arrays.
        f.write("-- 2. backup-lid -> current-lid translation lookup\n")
        f.write("CREATE TEMP TABLE _label_xlat (src_lid bigint PRIMARY KEY, name varchar(255));\n")
        used_src_lids = sorted({lid for dl in det_labels for lid in (dl["labels"] or [])})
        if used_src_lids:
            f.write("INSERT INTO _label_xlat (src_lid, name) VALUES\n  ")
            f.write(",\n  ".join(
                f"({lid}, {quote_text(src_lid_to_name[lid])})"
                for lid in used_src_lids
                if lid in src_lid_to_name
            ))
            f.write(";\n")
        f.write("\n")

        # Step 3: INSERT events
        f.write("-- 3. events\n")
        for e in events:
            cols = [
                "id", "type", "start", '"end"', '"cameraId"', '"partitionId"',
                "score", '"smartDetectTypes"', '"userId"', "metadata",
                '"deletedAt"', '"deletionType"', '"createdAt"', '"updatedAt"',
                "locked", '"thumbnailId"', '"thumbnailFullfovId"',
                '"packageThumbnailId"', '"packageThumbnailFullfovId"',
            ]
            vals = [
                quote_text(e["id"]),
                quote_text(e["type"]),
                str(e["start"]) if e["start"] is not None else "NULL",
                str(e["end"]) if e["end"] is not None else "NULL",
                quote_text(e["cameraId"]),
                quote_text(e["partitionId"]),
                str(e["score"]) if e["score"] is not None else "NULL",
                quote_json(e["smartDetectTypes"]),
                quote_text(e["userId"]),
                quote_json(e["metadata"]),
                f"'{e['deletedAt'].isoformat()}'::timestamptz" if e["deletedAt"] else "NULL",
                quote_text(e["deletionType"]),
                f"'{e['createdAt'].isoformat()}'::timestamptz",
                f"'{e['updatedAt'].isoformat()}'::timestamptz",
                "true" if e["locked"] else "false",
                quote_text(e["thumbnailId"]),
                quote_text(e["thumbnailFullfovId"]),
                quote_text(e["packageThumbnailId"]),
                quote_text(e["packageThumbnailFullfovId"]),
            ]
            f.write(
                f"INSERT INTO events ({', '.join(cols)}) "
                f"VALUES ({', '.join(vals)}) "
                f"ON CONFLICT (id) DO NOTHING;\n"
            )
        f.write("\n")

        # Step 4: INSERT detectionLabels with translated label arrays
        f.write("-- 4. detectionLabels (translated label arrays via _label_xlat -> labels)\n")
        for dl in det_labels:
            obj_id = quote_text(dl["objectId"])
            event_id = quote_text(dl["eventId"])
            src_lids = dl["labels"] or []
            if not src_lids:
                continue
            translated = "(SELECT array_agg(l.lid ORDER BY x.src_lid) " \
                         "FROM unnest(" + quote_int_array(src_lids) + ") AS x(src_lid) " \
                         "JOIN _label_xlat xlt ON xlt.src_lid = x.src_lid " \
                         "JOIN labels l ON l.name = xlt.name)"
            f.write(
                f'INSERT INTO "detectionLabels" '
                f'(id, "eventId", "objectId", labels, "createdAt", "updatedAt") '
                f'VALUES ({quote_text(dl["id"])}, {event_id}, {obj_id}, '
                f'{translated}, '
                f'\'{dl["createdAt"].isoformat()}\'::timestamptz, '
                f'\'{dl["updatedAt"].isoformat()}\'::timestamptz) '
                f'ON CONFLICT (id) DO NOTHING;\n'
            )
        f.write("\n")

        f.write("COMMIT;\n")
        f.write(f"\\echo 'restored {len(events)} events + {len(det_labels)} detectionLabels rows for camera={args.camera_id} on {args.date}'\n")

    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  events:           {len(events)}")
    print(f"  detectionLabels:  {len(det_labels)}")
    print(f"  new labels needed:{len(needed_label_names - set(current_label_to_lid))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
